"""
ca_memory.py — Project memory system for ca.

Maintains a `ca_memory/` directory alongside the project codebase that records:
  - file_registry.md  — per-file origin/history (what task created or last modified it)
  - task_log.md       — chronological log of every pipeline run
  - requirements/     — archived copies of every requirement file used

The key consumer is the pipeline reviewer, which receives a pre-run vs post-run
file diff so it knows which files pre-existed the current run (treat as ground truth)
vs which files the implementer just created or modified (review thoroughly).

This solves the root cause of the FormCheck calibrator.py destruction: the reviewer
had no way to know that a 208-line hand-crafted file was pre-existing, not a stub.
"""
from __future__ import annotations

import hashlib
import re
import shutil
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from .logger import get_logger

log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_SNAP_EXTENSIONS: frozenset[str] = frozenset({
    ".py", ".js", ".ts", ".tsx", ".jsx",
    ".html", ".css", ".scss",
    ".toml", ".json", ".yaml", ".yml",
    ".rs", ".go", ".java", ".rb", ".c", ".cpp", ".h",
    ".md", ".txt",
})

_SNAP_EXCLUDE_DIRS: frozenset[str] = frozenset({
    ".git", "__pycache__", "node_modules", ".venv", "venv", "env",
    "dist", "build", "wheels", ".eggs",
    ".chroma", "ca_logs", "logs", "tmp", "temp",
    ".ca_pipeline",   # pipeline's own per-run artifacts
    "ca_memory",      # don't snapshot our own output — would be circular
    ".pytest_cache", ".mypy_cache", ".ruff_cache", "htmlcov",
    ".idea", ".vscode",
})

# Files that are always regenerated and should not be tracked
_SNAP_EXCLUDE_NAMES: frozenset[str] = frozenset({
    "code_assistant.md",      # regenerated by project_context.py
    "code_assistant.md.tmp",
})

_REGISTRY_FILENAME = "file_registry.md"
_TASKLOG_FILENAME  = "task_log.md"
_REQUIREMENTS_DIR  = "requirements"


# ---------------------------------------------------------------------------
# FileSnapshot dataclass
# ---------------------------------------------------------------------------

@dataclass
class FileSnapshot:
    """Lightweight snapshot of one file at a point in time."""
    path: str           # relative to project root, forward slashes
    lines: int
    sha256_short: str   # first 12 hex chars — enough for change detection
    mtime: str          # ISO date (YYYY-MM-DD)

    def changed_from(self, other: "FileSnapshot") -> bool:
        """Return True if this snapshot differs from `other` (same path)."""
        return self.sha256_short != other.sha256_short

    def summary(self) -> str:
        return f"{self.path} ({self.lines} lines, {self.sha256_short})"


# ---------------------------------------------------------------------------
# CaMemory
# ---------------------------------------------------------------------------

class CaMemory:
    """Manages the ca_memory/ directory for a project.

    Parameters
    ----------
    directory : Path | None
        Project root directory. Defaults to Path.cwd().
    memory_dir_name : str
        Name of the memory subdirectory. Default: "ca_memory".
    """

    def __init__(
        self,
        directory: Path | None = None,
        memory_dir_name: str = "ca_memory",
    ) -> None:
        self._root = (directory or Path.cwd()).resolve()
        self._mem  = self._root / memory_dir_name
        log.debug("CaMemory initialised — root=%s mem=%s", self._root, self._mem)

    # ------------------------------------------------------------------
    # Public: snapshot
    # ------------------------------------------------------------------

    def snapshot_files(self) -> dict[str, FileSnapshot]:
        """Return a snapshot of all tracked source files under the project root.

        Returns
        -------
        dict[str, FileSnapshot]
            Keys are POSIX-style paths relative to the project root.
        """
        result: dict[str, FileSnapshot] = {}
        for abs_path in self._iter_source_files():
            rel = abs_path.relative_to(self._root).as_posix()
            try:
                raw   = abs_path.read_bytes()
                lines = raw.count(b"\n") + 1
                sha   = hashlib.sha256(raw).hexdigest()[:12]
                mtime = datetime.fromtimestamp(abs_path.stat().st_mtime).strftime("%Y-%m-%d")
                result[rel] = FileSnapshot(path=rel, lines=lines, sha256_short=sha, mtime=mtime)
            except OSError as exc:
                log.debug("snapshot_files: skipping %s — %s", rel, exc)
        log.debug("snapshot_files: %d files captured", len(result))
        return result

    # ------------------------------------------------------------------
    # Public: reviewer context
    # ------------------------------------------------------------------

    def format_reviewer_context(
        self,
        pre_snap: dict[str, FileSnapshot],
        post_snap: dict[str, FileSnapshot],
    ) -> str:
        """Format a context block for injection into the reviewer's prompt.

        Categorises files as:
          - Pre-existing and unchanged (treat as ground truth)
          - Pre-existing and modified by the implementer (review changes only)
          - Newly created by the implementer (review thoroughly)

        Parameters
        ----------
        pre_snap
            Snapshot taken before the pipeline run (before the implementer wrote anything).
        post_snap
            Snapshot taken after the implementer phase completed.
        """
        pre_keys  = set(pre_snap)
        post_keys = set(post_snap)

        new_files      = sorted(post_keys - pre_keys)
        modified_files = sorted(
            k for k in (pre_keys & post_keys)
            if post_snap[k].changed_from(pre_snap[k])
        )
        unchanged_files = sorted(
            k for k in (pre_keys & post_keys)
            if not post_snap[k].changed_from(pre_snap[k])
        )

        # Load origin info from file_registry if available
        registry = self._load_registry()

        lines = [
            "## Codebase History",
            "",
            "This block describes which files pre-existed this pipeline run and which",
            "were created or modified by the current implementer.",
            "**Read this before reviewing any file.**",
            "",
        ]

        if unchanged_files:
            lines.append("### Pre-existing files (unchanged by this run)")
            lines.append(
                "These files existed before the run. **Do not flag their pre-existing logic**"
                " as stubs or incomplete implementations — they are established code."
                " Only flag issues that the current implementer directly caused."
            )
            lines.append("")
            for f in unchanged_files:
                snap = pre_snap[f]
                origin = registry.get(f, {}).get("origin", "unknown task")
                lines.append(f"- `{f}` ({snap.lines} lines, origin: {origin})")
            lines.append("")

        if modified_files:
            lines.append("### Modified by the implementer (this run)")
            lines.append(
                "These files had working content before this run."
                " Focus your review on **what changed**, not the entire file."
                " Only flag regressions or incomplete additions."
            )
            lines.append("")
            for f in modified_files:
                pre  = pre_snap[f]
                post = post_snap[f]
                delta = post.lines - pre.lines
                sign  = "+" if delta >= 0 else ""
                lines.append(f"- `{f}` ({pre.lines} → {post.lines} lines, {sign}{delta})")
            lines.append("")

        if new_files:
            lines.append("### Newly created by the implementer (this run)")
            lines.append(
                "These files did not exist before the run."
                " **Review these thoroughly** for stubs, missing imports, and correctness."
            )
            lines.append("")
            for f in new_files:
                snap = post_snap[f]
                lines.append(f"- `{f}` ({snap.lines} lines)")
            lines.append("")

        if not pre_snap:
            lines.append(
                "_Note: No pre-run snapshot was available (first-ever run or ca_memory/ "
                "not yet initialised). Treat all files as potentially new._"
            )
            lines.append("")

        log.info(
            "format_reviewer_context: unchanged=%d modified=%d new=%d",
            len(unchanged_files), len(modified_files), len(new_files),
        )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Public: update after pipeline run
    # ------------------------------------------------------------------

    def update_from_pipeline(
        self,
        task: str,
        req_file_path: str | None,
        pre_snap: dict[str, FileSnapshot],
        post_snap: dict[str, FileSnapshot],
        outcome: str,
    ) -> None:
        """Update ca_memory/ after a pipeline run.

        Actions:
          1. Append a row to task_log.md
          2. Update file_registry.md for all new/modified files
          3. Archive the req file to requirements/ if one was used

        Parameters
        ----------
        task        : str   — The user task string (first 120 chars used)
        req_file_path: str | None — Path to the --req-file used (may be None)
        pre_snap    : snapshot before the run
        post_snap   : snapshot after the run
        outcome     : "PASS" | "FAIL" | "PARTIAL" | "UNKNOWN"
        """
        try:
            self._mem.mkdir(parents=True, exist_ok=True)
            self._update_task_log(task, req_file_path, pre_snap, post_snap, outcome)
            self._update_file_registry(task, pre_snap, post_snap)
            if req_file_path:
                self._archive_req_file(req_file_path)
            log.info(
                "ca_memory updated — task=%s outcome=%s",
                task[:60], outcome,
            )
        except Exception as exc:
            log.warning("ca_memory.update_from_pipeline failed (non-fatal): %s", exc)

    # ------------------------------------------------------------------
    # Internal: task log
    # ------------------------------------------------------------------

    def _update_task_log(
        self,
        task: str,
        req_file_path: str | None,
        pre_snap: dict[str, FileSnapshot],
        post_snap: dict[str, FileSnapshot],
        outcome: str,
    ) -> None:
        log_path = self._mem / _TASKLOG_FILENAME
        pre_keys  = set(pre_snap)
        post_keys = set(post_snap)

        new_files = sorted(post_keys - pre_keys)
        modified  = sorted(
            k for k in (pre_keys & post_keys)
            if post_snap[k].changed_from(pre_snap[k])
        )

        today        = date.today().isoformat()
        short_task   = task[:100].replace("|", "\\|").replace("\n", " ")
        req_name     = Path(req_file_path).name if req_file_path else "—"
        created_str  = ", ".join(Path(f).name for f in new_files) or "—"
        modified_str = ", ".join(Path(f).name for f in modified)  or "—"

        row = (
            f"| {today} | {short_task} | {req_name} "
            f"| {created_str} | {modified_str} | {outcome} |"
        )

        if not log_path.exists():
            header = (
                "# Task Log\n\n"
                "> Append-only log of all ca pipeline runs. Do not edit manually.\n\n"
                "| Date | Task | Req File | Files Created | Files Modified | Outcome |\n"
                "|------|------|----------|---------------|----------------|---------|\n"
            )
            log_path.write_text(header + row + "\n", encoding="utf-8")
        else:
            with log_path.open("a", encoding="utf-8") as f:
                f.write(row + "\n")

        log.debug("task_log: appended row for %s", today)

    # ------------------------------------------------------------------
    # Internal: file registry
    # ------------------------------------------------------------------

    def _update_file_registry(
        self,
        task: str,
        pre_snap: dict[str, FileSnapshot],
        post_snap: dict[str, FileSnapshot],
    ) -> None:
        registry_path = self._mem / _REGISTRY_FILENAME
        registry      = self._load_registry()
        today         = date.today().isoformat()
        short_task    = task[:80].replace("|", "\\|").replace("\n", " ")

        pre_keys  = set(pre_snap)
        post_keys = set(post_snap)
        changed   = {
            k for k in post_keys
            if k not in pre_keys or post_snap[k].changed_from(pre_snap.get(k, post_snap[k]))
        }

        for path in sorted(changed):
            snap = post_snap[path]
            existing = registry.get(path, {})
            registry[path] = {
                "lines":        snap.lines,
                "sha256":       snap.sha256_short,
                "origin":       existing.get("origin", short_task),
                "last_task":    short_task,
                "last_date":    today,
            }

        # Render and write
        lines = [
            "# File Registry",
            "",
            "> Updated after each ca pipeline run. Do not edit manually.",
            "",
            "| File | Lines | SHA-256 | Origin Task | Last Modified Task | Date |",
            "|------|-------|---------|-------------|-------------------|------|",
        ]
        for path in sorted(registry):
            r = registry[path]
            safe_path = path.replace("|", "\\|")
            lines.append(
                f"| {safe_path} | {r['lines']} | {r['sha256']} "
                f"| {r['origin']} | {r['last_task']} | {r['last_date']} |"
            )
        lines.append("")

        registry_path.write_text("\n".join(lines), encoding="utf-8")
        log.debug("file_registry: updated %d entries (%d changed)", len(registry), len(changed))

    def _load_registry(self) -> dict[str, dict]:
        """Parse file_registry.md into a dict keyed by file path."""
        registry_path = self._mem / _REGISTRY_FILENAME
        if not registry_path.exists():
            return {}

        result: dict[str, dict] = {}
        try:
            text = registry_path.read_text(encoding="utf-8")
            for line in text.splitlines():
                # Match table rows: | file | lines | sha | origin | last_task | date |
                if not line.startswith("|") or line.startswith("| File") or line.startswith("|---"):
                    continue
                parts = [p.strip() for p in line.strip("|").split("|")]
                if len(parts) < 6:
                    continue
                path = parts[0].replace("\\|", "|")
                try:
                    result[path] = {
                        "lines":     int(parts[1]),
                        "sha256":    parts[2],
                        "origin":    parts[3],
                        "last_task": parts[4],
                        "last_date": parts[5],
                    }
                except (ValueError, IndexError):
                    continue
        except Exception as exc:
            log.debug("_load_registry: parse error (non-fatal): %s", exc)

        return result

    # ------------------------------------------------------------------
    # Internal: req file archival
    # ------------------------------------------------------------------

    def _archive_req_file(self, req_file_path: str) -> None:
        src = Path(req_file_path)
        if not src.exists():
            log.debug("_archive_req_file: source not found — %s", req_file_path)
            return

        req_dir = self._mem / _REQUIREMENTS_DIR
        req_dir.mkdir(parents=True, exist_ok=True)

        ts   = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        dest = req_dir / f"{ts}_{src.name}"
        shutil.copy2(src, dest)
        log.info("ca_memory: archived req file %s → %s", src.name, dest.name)

    # ------------------------------------------------------------------
    # Internal: file iteration
    # ------------------------------------------------------------------

    def _iter_source_files(self):
        """Yield Path objects for all tracked source files under the project root."""
        for abs_path in self._root.rglob("*"):
            if not abs_path.is_file():
                continue
            if abs_path.name in _SNAP_EXCLUDE_NAMES:
                continue
            # Check none of the parent directories are excluded
            rel_parts = abs_path.relative_to(self._root).parts
            if any(part in _SNAP_EXCLUDE_DIRS for part in rel_parts):
                continue
            if abs_path.suffix.lower() not in _SNAP_EXTENSIONS:
                continue
            yield abs_path

    # ------------------------------------------------------------------
    # Public: load task log for REPL context
    # ------------------------------------------------------------------

    def task_log_content(self) -> str | None:
        """Return the content of task_log.md, or None if it doesn't exist."""
        log_path = self._mem / _TASKLOG_FILENAME
        if not log_path.exists():
            return None
        try:
            return log_path.read_text(encoding="utf-8")
        except Exception as exc:
            log.debug("task_log_content: read failed — %s", exc)
            return None
