"""
Per-project AI memory file: code_assistant.md

On the first `ca` launch in any directory a `code_assistant.md` file is
auto-generated by scanning project metadata (pyproject.toml / package.json /
directory structure).  No LLM call is needed.

The file is loaded into context at the start of every session so the AI has
persistent knowledge of the project.  After every pipeline run it is fully
regenerated with updated architecture, key files, build status and work
history.  After `ca --spec /finalize` the Open Requirements section is
updated with the new spec's acceptance criteria.

All methods are non-fatal: errors are logged as warnings and silently
swallowed so they never abort a pipeline run or REPL session.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .agents.base import Message
    from .agents.pipeline import PipelineState


# ---------------------------------------------------------------------------
# DiscoveryResult
# ---------------------------------------------------------------------------

@dataclass
class DiscoveryResult:
    """Metadata extracted from the project root without any LLM call."""
    name: str
    project_type: str            # "python" | "node" | "other"
    description: str
    language: str                # "Python" | "JavaScript/TypeScript" | "Unknown"
    package_manager: str         # "uv" | "pip" | "npm" | "yarn" | "unknown"
    test_runner: str             # "pytest" | "jest" | "vitest" | "unknown"
    key_dependencies: list[str] = field(default_factory=list)
    entry_points: list[str]      = field(default_factory=list)
    module_layout: list[str]     = field(default_factory=list)
    key_files: list[str]         = field(default_factory=list)


# ---------------------------------------------------------------------------
# ProjectScanner
# ---------------------------------------------------------------------------

class ProjectScanner:
    """Scan a project root directory and return a DiscoveryResult.

    No LLM is called.  All parsing is done with stdlib modules
    (tomllib, json, pathlib, re).
    """

    def scan(self, root: Path) -> DiscoveryResult:
        result = self._try_python(root)
        if result is None:
            result = self._try_node(root)
        if result is None:
            result = self._fallback(root)

        # Module layout: top-level dirs (skip hidden, __pycache__, *.egg-info,
        # and common runtime/artifact directories that aren't source modules)
        _LAYOUT_EXCLUDE = frozenset({
            "__pycache__", "node_modules",
            # build / dist artefacts
            "dist", "build", "wheels",
            # runtime / generated directories
            "ca_logs", "logs", "tmp", "temp",
            # test / coverage artefacts
            ".pytest_cache", ".mypy_cache", ".ruff_cache", "htmlcov",
        })
        result.module_layout = [
            p.name
            for p in sorted(root.iterdir())
            if p.is_dir()
            and not p.name.startswith(".")
            and p.name not in _LAYOUT_EXCLUDE
            and not p.name.endswith(".egg-info")
        ][:8]

        # Well-known key files
        candidates = [
            "README.md", "README.rst",
            "CLAUDE.md",                                # AI developer context
            "Makefile", "Dockerfile",
            "docker-compose.yml", "docker-compose.yaml",
            ".github/workflows",
        ]
        result.key_files = [c for c in candidates if (root / c).exists()]

        return result

    # ------------------------------------------------------------------
    # Python (pyproject.toml)
    # ------------------------------------------------------------------

    def _try_python(self, root: Path) -> DiscoveryResult | None:
        ppt = root / "pyproject.toml"
        if not ppt.exists():
            return None

        try:
            import tomllib
            data = tomllib.loads(ppt.read_text(encoding="utf-8"))
        except Exception:
            return None

        project = data.get("project", {})
        name = project.get("name", root.name)
        description = project.get("description", "")

        raw_deps: list[str] = []
        for dep in project.get("dependencies", []):
            # strip version specifiers: "rich>=13.0" → "rich"
            pkg = re.split(r"[>=<!;\[,\s]", dep)[0].strip()
            if pkg:
                raw_deps.append(pkg)
        key_deps = raw_deps[:10]

        # Entry points from [project.scripts]
        scripts = project.get("scripts", {})
        entry_points = [f"{k} = {v}" for k, v in scripts.items()]

        # Test runner detection — check main deps, ALL optional dep groups,
        # and [tool.pytest.ini_options] / [tool.pytest] presence.
        optional_deps: list[str] = []
        for group_deps in project.get("optional-dependencies", {}).values():
            for dep in group_deps:
                pkg = re.split(r"[>=<!;\[,\s]", dep)[0].strip()
                if pkg:
                    optional_deps.append(pkg)

        all_deps = [d.lower() for d in raw_deps + optional_deps]
        if any("pytest" in d for d in all_deps):
            test_runner = "pytest"
        elif "tool" in data and "pytest" in data.get("tool", {}):
            # [tool.pytest.ini_options] or [tool.pytest] section present
            test_runner = "pytest"
        else:
            test_runner = "unknown"

        # Package manager detection
        if (root / "uv.lock").exists():
            package_manager = "uv"
        elif (root / "poetry.lock").exists():
            package_manager = "poetry"
        else:
            package_manager = "pip"

        return DiscoveryResult(
            name=name,
            project_type="python",
            description=description,
            language="Python",
            package_manager=package_manager,
            test_runner=test_runner,
            key_dependencies=key_deps,
            entry_points=entry_points,
        )

    # ------------------------------------------------------------------
    # Node (package.json)
    # ------------------------------------------------------------------

    def _try_node(self, root: Path) -> DiscoveryResult | None:
        pkg_json = root / "package.json"
        if not pkg_json.exists():
            return None

        try:
            data = json.loads(pkg_json.read_text(encoding="utf-8"))
        except Exception:
            return None

        name = data.get("name", root.name)
        description = data.get("description", "")

        deps: dict = {}
        deps.update(data.get("dependencies", {}))
        deps.update(data.get("devDependencies", {}))
        key_deps = list(deps.keys())[:10]

        # Test runner
        dep_names = [d.lower() for d in deps]
        if "jest" in dep_names:
            test_runner = "jest"
        elif "vitest" in dep_names:
            test_runner = "vitest"
        else:
            scripts = data.get("scripts", {})
            test_cmd = scripts.get("test", "")
            if "jest" in test_cmd:
                test_runner = "jest"
            elif "vitest" in test_cmd:
                test_runner = "vitest"
            else:
                test_runner = "unknown"

        # Package manager
        if (root / "yarn.lock").exists():
            package_manager = "yarn"
        elif (root / "pnpm-lock.yaml").exists():
            package_manager = "pnpm"
        else:
            package_manager = "npm"

        # Language detection
        lang = "JavaScript/TypeScript" if (root / "tsconfig.json").exists() else "JavaScript"

        # Entry points
        main = data.get("main", "")
        entry_points = [main] if main else []

        return DiscoveryResult(
            name=name,
            project_type="node",
            description=description,
            language=lang,
            package_manager=package_manager,
            test_runner=test_runner,
            key_dependencies=key_deps,
            entry_points=entry_points,
        )

    # ------------------------------------------------------------------
    # Fallback
    # ------------------------------------------------------------------

    def _fallback(self, root: Path) -> DiscoveryResult:
        return DiscoveryResult(
            name=root.name,
            project_type="other",
            description="",
            language="Unknown",
            package_manager="unknown",
            test_runner="unknown",
        )


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

def _extract_files_written(impl_history: list["Message"]) -> list[str]:
    """Return an ordered, deduplicated list of files written/edited by the implementer."""
    seen: set[str] = set()
    result: list[str] = []
    for msg in impl_history:
        if not (msg.role == "assistant" and msg.tool_calls):
            continue
        for tc in msg.tool_calls:
            fn = tc.get("function", {})
            if fn.get("name") not in ("write_file", "edit_file"):
                continue
            args = fn.get("arguments", {})
            if isinstance(args, str):
                try:
                    args = json.loads(args)
                except Exception:
                    continue
            path = args.get("path", "")
            if path and path not in seen:
                seen.add(path)
                result.append(path)
    return result


# Regex matching the same pattern used in pipeline.py
_VERDICT_FAIL = re.compile(
    r"(?:##\s*|\*\*)?Overall\s+Verdict(?:\*\*)?[:\*\s]*\n?\s*(FAIL|PARTIAL)",
    re.IGNORECASE,
)
_FAIL_ROW = re.compile(r"\|\s*(.+?)\s*\|\s*FAIL\s*\|\s*(.+?)\s*\|", re.IGNORECASE)


def _parse_test_verdict(test_results: str) -> str:
    """Return 'PASS', 'FAIL', or 'PARTIAL' from tester output."""
    if not test_results:
        return "UNKNOWN"
    m = _VERDICT_FAIL.search(test_results)
    if m:
        return m.group(1).upper()
    # If the tester ran and produced output without the FAIL/PARTIAL keyword, assume PASS
    if test_results.strip():
        return "PASS"
    return "UNKNOWN"


def _parse_acceptance_criteria(
    criteria_text: str,
    test_results: str,
) -> list[tuple[str, str]]:
    """
    Return list of (criterion, result) pairs.

    result is 'PASS', 'FAIL', or 'UNKNOWN'.
    """
    if not criteria_text.strip():
        return []

    # Collect failing criterion strings from test table rows
    failing: set[str] = set()
    for m in _FAIL_ROW.finditer(test_results):
        failing.add(m.group(1).strip().lower())

    pairs: list[tuple[str, str]] = []
    for line in criteria_text.splitlines():
        line = line.strip()
        # Skip blank lines and pure markdown formatting
        if not line or line.startswith("#") or line == "---":
            continue
        # Strip leading list markers: "1.", "-", "*", "[ ]", "[x]"
        criterion = re.sub(r"^(\d+\.|[-*]|\[[ x]\])\s*", "", line).strip()
        if not criterion:
            continue
        if criterion.lower() in failing:
            verdict = "FAIL"
        elif test_results and _parse_test_verdict(test_results) == "PASS":
            verdict = "PASS"
        else:
            verdict = "UNKNOWN"
        pairs.append((criterion, verdict))

    return pairs


def _summarise_arch_plan(arch_plan: str, max_chars: int = 1200) -> str:
    """Truncate arch_plan at a paragraph boundary within max_chars."""
    if len(arch_plan) <= max_chars:
        return arch_plan
    # Try to cut at a double-newline (paragraph boundary)
    truncated = arch_plan[:max_chars]
    last_para = truncated.rfind("\n\n")
    if last_para > max_chars // 2:
        truncated = truncated[:last_para]
    return truncated.rstrip() + "\n\n*(truncated)*"


def _parse_spec_criteria(spec_content: str) -> list[str]:
    """
    Extract acceptance criteria lines from a spec document.

    Looks for a section headed "Acceptance Criteria" and returns the
    non-empty, non-heading lines underneath it until the next section.
    Falls back to returning numbered/bulleted lines if no section found.
    """
    # Try to find "Acceptance Criteria" section
    ac_section = re.search(
        r"(?:^|\n)#+\s*Acceptance Criteria\s*\n(.*?)(?=\n#+\s|\Z)",
        spec_content,
        re.DOTALL | re.IGNORECASE,
    )
    if ac_section:
        block = ac_section.group(1)
    else:
        block = spec_content

    criteria: list[str] = []
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Accept numbered list items or bullet items
        if re.match(r"^(\d+\.|[-*]|\[[ x]\])\s+", line):
            criterion = re.sub(r"^(\d+\.|[-*]|\[[ x]\])\s*", "", line).strip()
            if criterion:
                criteria.append(criterion)

    return criteria


def _extract_work_history(existing_content: str) -> list[str]:
    """
    Pull existing work history rows out of a code_assistant.md file.

    Returns a list of raw markdown table row strings (without the leading |).
    """
    history_section = re.search(
        r"##\s*Work History\s*\n(.*?)(?=\n##\s|\Z)",
        existing_content,
        re.DOTALL,
    )
    if not history_section:
        return []
    rows: list[str] = []
    for line in history_section.group(1).splitlines():
        line = line.strip()
        # Skip header row and separator row
        if line.startswith("| Date") or line.startswith("|---") or not line.startswith("|"):
            continue
        rows.append(line)
    return rows


# ---------------------------------------------------------------------------
# ProjectContext
# ---------------------------------------------------------------------------

class ProjectContext:
    """
    Manages the code_assistant.md file in a project directory.

    Parameters
    ----------
    directory : Path | None
        Project root.  Defaults to Path.cwd().
    """

    def __init__(self, directory: Path | None = None) -> None:
        from .config import config
        self._dir = directory or Path.cwd()
        self._path = self._dir / config.project_context_file
        self._scanner = ProjectScanner()

    # ------------------------------------------------------------------
    # Basic accessors
    # ------------------------------------------------------------------

    def exists(self) -> bool:
        return self._path.exists()

    def read(self) -> str:
        try:
            return self._path.read_text(encoding="utf-8")
        except Exception:
            return ""

    # ------------------------------------------------------------------
    # ensure() — silent first-run discovery
    # ------------------------------------------------------------------

    def ensure(self) -> bool:
        """
        Generate code_assistant.md if it doesn't exist yet.

        Returns True if the file was created, False if it already existed.
        Silent — no console output.
        """
        if self._path.exists():
            return False

        result = self._scanner.scan(self._dir)
        content = self._render_initial(result)
        self._write(content)
        return True

    # ------------------------------------------------------------------
    # update_from_pipeline() — post-pipeline regeneration
    # ------------------------------------------------------------------

    def update_from_pipeline(
        self,
        state: "PipelineState",
        task: str,
    ) -> None:
        """
        Fully regenerate code_assistant.md after a pipeline run.

        Preserves the Work History section (appends a new row).
        Preserves the Open Requirements section if one exists.
        """
        existing = self.read()
        prev_history_rows = _extract_work_history(existing)

        # Attempt discovery; fall back to bare minimum if it fails
        try:
            discovery = self._scanner.scan(self._dir)
        except Exception:
            discovery = DiscoveryResult(
                name=self._dir.name,
                project_type="other",
                description="",
                language="Unknown",
                package_manager="unknown",
                test_runner="unknown",
            )

        verdict = _parse_test_verdict(state.test_results)
        criteria_pairs = _parse_acceptance_criteria(
            state.acceptance_criteria, state.test_results
        )
        files_written = _extract_files_written(state.impl_history)
        arch_summary = _summarise_arch_plan(state.arch_plan)

        # Build new history row
        today = date.today().isoformat()
        short_task = task[:80].replace("|", "\\|")
        new_row = f"| {today} | {short_task} | {verdict} |"
        history_rows = prev_history_rows + [new_row]

        # Preserve Open Requirements from previous file
        open_req = self._extract_section(existing, "Open Requirements")

        content = self._render_pipeline(
            discovery=discovery,
            arch_summary=arch_summary,
            files_written=files_written,
            verdict=verdict,
            criteria_pairs=criteria_pairs,
            history_rows=history_rows,
            open_requirements=open_req,
        )
        self._write(content)

    # ------------------------------------------------------------------
    # update_from_spec() — post-spec update
    # ------------------------------------------------------------------

    def update_from_spec(
        self,
        spec_path: Path,
        spec_content: str,
    ) -> None:
        """
        Update the Open Requirements section after ca --spec /finalize.

        All other sections are preserved from the existing file.
        """
        existing = self.read()

        criteria = _parse_spec_criteria(spec_content)

        if not criteria:
            open_req_content = f"See {spec_path.name} for full spec."
        else:
            lines = [f"From `{spec_path.name}`:"]
            for c in criteria:
                lines.append(f"- [ ] {c}")
            open_req_content = "\n".join(lines)

        # Replace (or append) the Open Requirements section
        if "## Open Requirements" in existing:
            new_content = re.sub(
                r"(## Open Requirements\s*\n)(.*?)(\Z|(?=\n## ))",
                f"\\1{open_req_content}\n",
                existing,
                flags=re.DOTALL,
            )
        else:
            new_content = existing.rstrip() + f"\n\n## Open Requirements\n\n{open_req_content}\n"

        self._write(new_content)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _write(self, content: str) -> None:
        """Atomic write: write to .tmp then rename."""
        self._path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self._path.with_suffix(".md.tmp")
        tmp.write_text(content, encoding="utf-8")
        tmp.replace(self._path)

    def _extract_section(self, content: str, section_name: str) -> str:
        """Extract the body of a ## section from a markdown string."""
        m = re.search(
            rf"## {re.escape(section_name)}\s*\n(.*?)(\Z|(?=\n## ))",
            content,
            re.DOTALL,
        )
        return m.group(1).strip() if m else ""

    def _render_initial(self, r: DiscoveryResult) -> str:
        """Render the initial code_assistant.md (first-run, no build info yet)."""
        lines = [
            f"# Project: {r.name}",
            "",
            "> Auto-generated by code-assistant. "
            "Do not edit manually — it will be overwritten after each pipeline run.",
            "",
            "## Project",
            "",
            f"- **Type**: {r.project_type.title()} ({_project_type_file(r.project_type)})",
            f"- **Language**: {r.language}",
        ]
        if r.description:
            lines.append(f"- **Description**: {r.description}")
        lines += [
            f"- **Package manager**: {r.package_manager}",
            f"- **Test runner**: {r.test_runner}",
        ]
        if r.entry_points:
            lines.append(f"- **Entry points**: {', '.join(f'`{e}`' for e in r.entry_points[:5])}")
        if r.key_dependencies:
            lines.append(f"- **Key dependencies**: {', '.join(r.key_dependencies)}")
        lines.append("")

        if r.module_layout:
            lines += ["## Module Layout", ""]
            for d in r.module_layout:
                lines.append(f"- {d}/")
            lines.append("")

        if r.key_files:
            lines += ["## Key Files", ""]
            for f in r.key_files:
                lines.append(f"- {f}")
            lines.append("")

        lines += [
            "## Current Status",
            "",
            "Not yet built by code-assistant.",
            "",
            "## Work History",
            "",
            "| Date | Task | Outcome |",
            "|------|------|---------|",
            "",
            "## Open Requirements",
            "",
            "*(populated after `ca --spec /finalize`)*",
            "",
        ]
        return "\n".join(lines)

    def _render_pipeline(
        self,
        discovery: DiscoveryResult,
        arch_summary: str,
        files_written: list[str],
        verdict: str,
        criteria_pairs: list[tuple[str, str]],
        history_rows: list[str],
        open_requirements: str,
    ) -> str:
        """Render code_assistant.md after a pipeline run."""
        lines = [
            f"# Project: {discovery.name}",
            "",
            "> Auto-generated by code-assistant. "
            "Do not edit manually — it will be overwritten after each pipeline run.",
            "",
            "## Project",
            "",
            f"- **Type**: {discovery.project_type.title()} "
            f"({_project_type_file(discovery.project_type)})",
            f"- **Language**: {discovery.language}",
        ]
        if discovery.description:
            lines.append(f"- **Description**: {discovery.description}")
        lines += [
            f"- **Package manager**: {discovery.package_manager}",
            f"- **Test runner**: {discovery.test_runner}",
        ]
        if discovery.entry_points:
            lines.append(
                f"- **Entry points**: {', '.join(f'`{e}`' for e in discovery.entry_points[:5])}"
            )
        if discovery.key_dependencies:
            lines.append(f"- **Key dependencies**: {', '.join(discovery.key_dependencies)}")
        lines.append("")

        if discovery.module_layout:
            lines += ["## Module Layout", ""]
            for d in discovery.module_layout:
                lines.append(f"- {d}/")
            lines.append("")

        if arch_summary:
            lines += ["## Architecture", ""]
            lines.append(arch_summary)
            lines.append("")

        if files_written:
            lines += ["## Key Files", ""]
            for f in files_written:
                lines.append(f"- {f}")
            lines.append("")

        # Current Status
        today = date.today().isoformat()
        status_icons = {"PASS": "✓", "FAIL": "✗", "PARTIAL": "~", "UNKNOWN": "?"}
        icon = status_icons.get(verdict, "?")
        if verdict == "PASS":
            status_line = f"**{icon} PASS** — all acceptance criteria passed ({today})"
        elif verdict in ("FAIL", "PARTIAL"):
            status_line = f"**{icon} {verdict}** — some criteria failed ({today})"
        else:
            status_line = f"**{icon} {verdict}** — outcome unknown ({today})"

        lines += ["## Current Status", "", status_line, ""]

        if criteria_pairs:
            lines += ["## Acceptance Criteria", ""]
            lines += ["| Criterion | Result |", "|-----------|--------|"]
            for criterion, result in criteria_pairs:
                safe = criterion.replace("|", "\\|")
                lines.append(f"| {safe} | {result} |")
            lines.append("")

        # Work History
        lines += ["## Work History", ""]
        lines += ["| Date | Task | Outcome |", "|------|------|---------|"]
        for row in history_rows:
            lines.append(row)
        lines.append("")

        # Open Requirements
        lines += ["## Open Requirements", ""]
        if open_requirements:
            lines.append(open_requirements)
        else:
            lines.append("*(none)*")
        lines.append("")

        return "\n".join(lines)


def _project_type_file(project_type: str) -> str:
    """Return the primary manifest file name for a project type."""
    return {
        "python": "pyproject.toml",
        "node": "package.json",
    }.get(project_type, "unknown")
